people = ["Mukhtar", "Tariq", "Maryam"]
print(people[:2])
print(people[:])
print(people[1:])
print(people[2:])
print(people[0])
print(people[-1])
print(people[::1])
print(people[::2])
print(people[::-1])