name = "Ibrahim Sadiq"
print(name[0:6])
print(name[:6])
print(name[:])
print(name[0])
print(name[-1])
print(name[-2])
print(name[8:])
print(name[:7])
print(name[::1])
print(name[::2])
print(name[::3])
print(name[::-1])
print(name[4:11])